const audios = [
  {
    category: 1,
    categoryName: 'Nano',
    imgId: 'nano',
    path: 'http://download856.mediafire.com/npform5n14vg/x8gp1ygav378ugt/eeee-jic.mp3',
    title: 'Eeeeeh',
  },
  {
    category: 2,
    categoryName: 'Lucas',
    imgId: 'lucas',
    path: 'http://download1475.mediafire.com/80cjqrbpb5qg/zvshkfjp0w71r53/perdona.mp3',
    title: 'Piloto chapecó',
  },
  {
    category: 3,
    categoryName: 'German',
    imgId: 'german',
    path: require('../assets/audio/agua-pozo.mp3'),
    title: 'Agua del pozo',
  },
  {
    category: 2,
    categoryName: 'Lucas',
    imgId: 'lucas',
    path: require('../assets/audio/alto-petardo.mp3'),
    title: 'Alto petardo',
  },
  {
    category: 2,
    categoryName: 'Lucas',
    imgId: 'lucas',
    path: require('../assets/audio/risa-gordo.mp3'),
    title: 'Risa Gordo',
  },
  {
    category: 2,
    categoryName: 'Lucas',
    imgId: 'lucas',
    path: require('../assets/audio/perdona.mp3'),
    title: 'Perdona',
  },
  {
    category: 0,
    categoryName: 'General',
    imgId: '',
    path: require('../assets/audio/canelones.mp3'),
    title: 'Canelones',
  },
  {
    category: 3,
    categoryName: 'German',
    imgId: 'german',
    path: require('../assets/audio/despedida-gratis.mp3'),
    title: 'Despedida Cavenaghi',
  },
  {
    category: 3,
    categoryName: 'German',
    imgId: 'german',
    path: require('../assets/audio/gordo-mion.mp3'),
    title: 'Gordo Mion',
  },
  {
    category: 3,
    categoryName: 'German',
    imgId: 'german',
    path: require('../assets/audio/gordo-mion-2.mp3'),
    title: 'Gordo Mion 2',
  },
  {
    category: 3,
    categoryName: 'German',
    imgId: 'german',
    path: require('../assets/audio/gordo-mion-3.mp3'),
    title: 'Gordo Mion 3',
  },
  {
    category: 2,
    categoryName: 'Lucas',
    imgId: 'lucas',
    path: require('../assets/audio/mensaje-peligro.mp3'),
    title: 'Mensaje, peligro',
  },
  {
    category: 0,
    categoryName: 'General',
    imgId: '',
    path: require('../assets/audio/piel-iguana.mp3'),
    title: 'Piel de Iguana',
  },
  {
    category: 2,
    categoryName: 'Lucas',
    imgId: 'lucas',
    path: require('../assets/audio/piloto-chapeco.mp3'),
    title: 'Piloto chapecoense',
  },
  {
    category: 3,
    categoryName: 'German',
    imgId: 'german',
    path: require('../assets/audio/publicacion-gordo.mp3'),
    title: 'Publicacion Gordo',
  },
  {
    category: 2,
    categoryName: 'Lucas',
    imgId: 'lucas',
    path: require('../assets/audio/tampon-mirtha.mp3'),
    title: 'Tampón Mirtha Legrand',
  },
  {
    category: 2,
    categoryName: 'Lucas',
    imgId: 'lucas',
    path: require('../assets/audio/tengo-sueter.mp3'),
    title: 'Tengo sueter',
  },
];

export default audios;
